### ISSUE TITLE
Bugs with Lobby Items and Ranks

### ISSUE THREAD

**Issue by ericbarbwire** [Bimmr/McInfected#103] opened 2016-10-14 19:14 UTC
Hello, I've already posted these bugs on the Spigot discussion threads, but I think it may be easier to compile all the issues onto a GitHub page.

Issue 1: in console each time someone interacts with an item. Whether they are in the game or not.
It's a nullpointer issue.
Full console error: http://hastebin.com/ravicehaya.vbs
This spams my console heavily.

Issue 2:
When I run the command /inf I don't receive a message or anything. It doesn't respond, in console I do get this console message.
http://hastebin.com/afepegesax.vbs

I run a Spigot 1.10.2 server.
Infected related plugins I run:
https://www.spigotmc.org/resources/mcinfected-ranks.2826/
https://www.spigotmc.org/resources/mcinfected-lobby-items.3202/
https://www.spigotmc.org/resources/mcinfected-leaderboard.8309/
https://www.spigotmc.org/resources/mcinfected-custom-signs.3201/
https://www.spigotmc.org/resources/mcinfected.2133/
https://www.spigotmc.org/resources/bimmcore.23074/
https://www.spigotmc.org/resources/libs-disguises.81/

Thank you so much, hope to see these issues fixed as the plugin is very fun to play!

**Comment by Bimmr** [comment] 2016-10-17 02:54
I'll look into once i get time. Schools getting busy.

**Comment by Bimmr** [comment] 2016-10-25 20:23
1. It doesn't actually say where the issue is, did you happen to get a better log of the error?

**Comment by ericbarbwire** [comment] 2016-11-03 17:31
Here are the messages I receive from starting up the server related to the Infected plugin: http://hastebin.com/susufudubo.apache

I'm not sure if I can get anymore information related to issue 1 though, unless there's something you'd like me to do to check?

Thanks :)

**Comment by ericbarbwire** [comment] 2016-11-07 22:47
I actually think I do have a better log of the error: http://hastebin.com/okafenahev.swift

Thanks

**Comment by Bimmr** [comment] 2017-01-07 18:28
I'm not able to get any error with Lobby Items, And things may have been changed since this was posted; So I'm going to have to close the issue, but if it happens again just make a new ticket.

**Closed by Bimmr** 2017-01-07 18:28 UTC
