### ISSUE TITLE
Bugged human kits

### ISSUE THREAD

**Issue by cpstest-tech** [Bimmr/McInfected#174] opened 2021-03-14 09:27 UTC
## What's Currently Happening
The kits randomly spawns in the grid and not follow a line and they leave random spaces

----
## Steps to Reproduce (for bugs)
This is the bug, this is my kits file
![Screenshot (7)](https://user-images.githubusercontent.com/68495386/111063420-a0b00c00-84ae-11eb-93e6-ec1931c4b7b7.png)

Kits.yml: https://pastebin.com/JrZhVZ6y

## Error Code
```
4.03 09:12:28 [Server] INFO Loaded Lobby: Lobby
14.03 09:12:28 [Server] INFO ----- Loaded Arena: SkyLoft
14.03 09:12:28 [Server] INFO ----- Loaded Arena: TheImaginaryZones
14.03 09:12:28 [Server] INFO Loaded Human Kit: Private
14.03 09:12:29 [Server] INFO Loaded Human Kit: Specialist
14.03 09:12:29 [Server] INFO Loaded Human Kit: Corporal
14.03 09:12:29 [Server] INFO Loaded Human Kit: Sergeant
14.03 09:12:29 [Server] INFO Loaded Human Kit: StaffSergeant
14.03 09:12:29 [Server] INFO Loaded Human Kit: MasterSergeant
14.03 09:12:29 [Server] INFO Loaded Human Kit: 1stSergeant
14.03 09:12:29 [Server] INFO Loaded Human Kit: SergeantMajor
14.03 09:12:29 [Server] INFO Loaded Human Kit: CommandSergeantMajor
14.03 09:12:29 [Server] INFO Loaded Human Kit: 2ndLieutenant
14.03 09:12:29 [Server] INFO Loaded Human Kit: 1stLieutenant
14.03 09:12:29 [Server] INFO Loaded Human Kit: Captain
14.03 09:12:29 [Server] INFO Loaded Human Kit: Lt_Colonel
14.03 09:12:29 [Server] INFO Loaded Human Kit: Colonel
14.03 09:12:29 [Server] INFO Loaded Human Kit: Brigadier_General
14.03 09:12:29 [Server] INFO Loaded Human Kit: Major
14.03 09:12:29 [Server] INFO Loaded Human Kit: MajorGeneral
14.03 09:12:29 [Server] INFO Loaded Infected Kit: Zombie
14.03 09:12:30 [Server] INFO Loaded Infected Kit: Skeleton
14.03 09:12:30 [Server] INFO Loaded Infected Kit: Witch
14.03 09:12:30 [Server] ERROR iDisguise does not support showing player names well disguised!
14.03 09:12:30 [Server] INFO For Disguise Support we're using iDisguise
14.03 09:12:30 [Server] INFO No chests were found
14.03 09:12:32 [Server] INFO PinguinoClapsYou issued server command: /join
14.03 09:12:43 [Server] INFO CONSOLE issued server command: /list 
14.03 09:12:43 [Server] INFO mvp+: PinguinoClapsYou
14.03 09:13:16 [Server] INFO PinguinoClapsYou issued server command: /mc admin reload
14.03 09:13:16 [Server] INFO Loaded Lobby: Lobby
14.03 09:13:16 [Server] INFO ----- Loaded Arena: SkyLoft
14.03 09:13:16 [Server] INFO ----- Loaded Arena: TheImaginaryZones
14.03 09:13:16 [Server] INFO Loaded Human Kit: Private
14.03 09:13:16 [Server] INFO Loaded Human Kit: Specialist
14.03 09:13:16 [Server] INFO Loaded Human Kit: Corporal
14.03 09:13:16 [Server] INFO Loaded Human Kit: Sergeant
14.03 09:13:16 [Server] INFO Loaded Human Kit: StaffSergeant
14.03 09:13:16 [Server] INFO Loaded Human Kit: MasterSergeant
14.03 09:13:16 [Server] INFO Loaded Human Kit: 1stSergeant
14.03 09:13:16 [Server] INFO Loaded Human Kit: SergeantMajor
14.03 09:13:16 [Server] INFO Loaded Human Kit: CommandSergeantMajor
14.03 09:13:16 [Server] INFO Loaded Human Kit: 2ndLieutenant
14.03 09:13:16 [Server] INFO Loaded Human Kit: 1stLieutenant
14.03 09:13:16 [Server] INFO Loaded Human Kit: Captain
14.03 09:13:17 [Server] INFO Loaded Human Kit: Lt_Colonel
14.03 09:13:17 [Server] INFO Loaded Human Kit: Colonel
14.03 09:13:17 [Server] INFO Loaded Human Kit: Brigadier_General
14.03 09:13:17 [Server] INFO Loaded Human Kit: Major
14.03 09:13:17 [Server] INFO Loaded Human Kit: MajorGeneral
14.03 09:13:17 [Server] INFO Loaded Infected Kit: Zombie
14.03 09:13:17 [Server] INFO Loaded Infected Kit: Skeleton
14.03 09:13:17 [Server] INFO Loaded Infected Kit: Witch
14.03 09:13:17 [Server] ERROR iDisguise does not support showing player names well disguised!
14.03 09:13:17 [Server] INFO For Disguise Support we're using iDisguise
14.03 09:13:17 [Server] INFO No chests were found

```

----
## Your Environment
* Spigot Version used: 1.12.2 
* McInfected Version: 1.6.7
* BimmCore Version: 1.0.7
* Any Addons?(Include their versions)
IDisguise 5.8.2
McInfected-Dedicated v0.2.1
McInfected - Lobby Items v1.1.1
Vault 1.5.6

**Comment by cpstest-tech** [comment] 2021-03-14 09:36
Apparently it goes out of luck, now after 3 restarts it is like this, still bugged but better
![Screenshot (8)](https://user-images.githubusercontent.com/68495386/111063835-174e0900-84b1-11eb-9384-5fb1ab01fd15.png)

**Comment by Bimmr** [comment] 2021-03-14 14:10
Could you put your Kits.yml on Pastebin or something similar so that
formatting can be copied so I can test?

**Comment by Bimmr** [comment] 2021-03-14 14:12
If I had to take a guess just by looking, it looks like the icons you used
for some kits is invalid and so it's showing up as blank spaces.

**Comment by cpstest-tech** [comment] 2021-03-14 14:12
I will do it

**Comment by cpstest-tech** [comment] 2021-03-14 14:16
https://pastebin.com/JrZhVZ6y

**Comment by cpstest-tech** [comment] 2021-03-14 14:17
done

**Comment by cpstest-tech** [comment] 2021-03-14 14:20
I have not changed the icons, they just randomly generated

**Comment by cpstest-tech** [comment] 2021-03-14 14:23
and this problem randomly showed up

**Comment by Bimmr** [comment] 2021-03-14 15:07
Would you also be able to do the same with your config.yml

**Comment by Bimmr** [comment] 2021-03-14 15:13
So it looks like the issue is that the Icons are trying to use items that aren't valid. If you can send me your server's IP and provide me (Bimmr) with the permission node **McInfected.Setup** I can log in and fix it for you.

**Comment by cpstest-tech** [comment] 2021-03-14 15:19
thanks! Also, do there are prestiges in the plugin?

**Comment by cpstest-tech** [comment] 2021-03-14 15:19
and how to change the kit not unlocked icon?

**Comment by paolosasso** [comment] 2021-03-14 15:21
and how to change the kit not unlocked icon?

**Comment by Bimmr** [comment] 2021-03-14 15:27
I was working on Prestiging in a re-write of the Ranks addon, however, I kept finding people leaking the plugin and so I've stopped working on updates and now only do bug fixes. 

There is no way to change the locked icon.

**Comment by cpstest-tech** [comment] 2021-03-14 15:30
How do can I do them?

**Comment by cpstest-tech** [comment] 2021-03-14 15:30
if it is possible

**Comment by Bimmr** [comment] 2021-03-14 15:34
The closest you can do to Prestiging would be to create ranks like:

Level 1
Level 2
Prestige Level 1
Prestige Level 2

If you want to fix the Kit's icons yourself you can do so through the **/McInfected Setup** command. Because that is the solution to this bug, I'm going to be closing the ticket. If you need more support you can join [Discord](https://discord.gg/6rxefEv), however, you will need to provide proof you have purchased the plugin (Spigot profile name).

**Closed as completed by Bimmr** 2021-03-14 15:34 UTC
