### ISSUE TITLE
Human Kit Selection is not working

### ISSUE THREAD

**Issue by zvvx** [Bimmr/McInfected#51] opened 2015-08-28 19:24 UTC
I am having trouble figuring out why I can't go into the human kit selection. I can go into the zombie selection fine.

The error log:
[15:20:26 ERROR]: Could not pass event PlayerInteractEvent to McInfected-LobbyItems v0.0.2
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-fdc1440-53fac9f]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-fdc1440-53fac9f]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-fdc1440-53fac9f]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-fdc1440-53fac9f]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:227) [spigot.jar:git-Spigot-fdc1440-53fac9f]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:194) [spigot.jar:git-Spigot-fdc1440-53fac9f]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:190) [spigot.jar:git-Spigot-fdc1440-53fac9f]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:717) [spigot.jar:git-Spigot-fdc1440-53fac9f]
	at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:52) [spigot.jar:git-Spigot-fdc1440-53fac9f]
	at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) [spigot.jar:git-Spigot-fdc1440-53fac9f]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-fdc1440-53fac9f]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_11]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_11]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot.jar:git-Spigot-fdc1440-53fac9f]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:714) [spigot.jar:git-Spigot-fdc1440-53fac9f]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-fdc1440-53fac9f]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [spigot.jar:git-Spigot-fdc1440-53fac9f]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [spigot.jar:git-Spigot-fdc1440-53fac9f]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_11]
Caused by: org.bukkit.command.CommandException: Unhandled exception executing command 'mcinfected' in plugin McInfected v1.2.5
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-fdc1440-53fac9f]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-fdc1440-53fac9f]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigot.jar:git-Spigot-fdc1440-53fac9f]
	at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.performCommand(CraftPlayer.java:242) ~[spigot.jar:git-Spigot-fdc1440-53fac9f]
	at me.bimmr.mcinfectedlobbyitems.Listeners.onClick(Listeners.java:50) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_11]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_11]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_11]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_11]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-fdc1440-53fac9f]
	... 18 more
Caused by: java.lang.NullPointerException
	at com.bimmr.mcinfected.MenuManager.openKitsMenu(MenuManager.java:97) ~[?:?]
	at com.bimmr.mcinfected.Command.SubCommands.KitCommand.execute(KitCommand.java:74) ~[?:?]
	at com.bimmr.mcinfected.Command.CHandler.onCommand(CHandler.java:98) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-fdc1440-53fac9f]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-fdc1440-53fac9f]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigot.jar:git-Spigot-fdc1440-53fac9f]
	at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.performCommand(CraftPlayer.java:242) ~[spigot.jar:git-Spigot-fdc1440-53fac9f]
	at me.bimmr.mcinfectedlobbyitems.Listeners.onClick(Listeners.java:50) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_11]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_11]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_11]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_11]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-fdc1440-53fac9f]
	... 18 more

**Comment by Bimmr** [comment] 2015-08-28 20:17
Are the human kits loading properly? Check the console when starting the
server to make sure they were loaded.

**Comment by zvvx** [comment] 2015-08-29 16:17
Yes they load properly. Maybe it's something with the kit setup.

![screen shot 2015-08-29 at 12 16 10 pm](https://cloud.githubusercontent.com/assets/10146393/9562933/e60eecd8-4e47-11e5-805a-a5bd1012a6c6.png)
![screen shot 2015-08-29 at 12 16 35 pm](https://cloud.githubusercontent.com/assets/10146393/9562935/e89d6826-4e47-11e5-87eb-92ae81502749.png)
![screen shot 2015-08-29 at 12 16 59 pm](https://cloud.githubusercontent.com/assets/10146393/9562936/eb1c9bbc-4e47-11e5-93ac-edfe91ad8d63.png)

**Comment by zvvx** [comment] 2015-08-29 16:29
And would it be possible to have no description for humans?

**Comment by Bimmr** [comment] 2015-08-29 16:50
Can you send me your kits.yml over spigot?

**Comment by Bimmr** [comment] 2015-08-29 16:50
And ya you should be able to just remove the description

**Comment by Bimmr** [comment] 2015-08-29 19:46
Do you have McInfected-Ranks on the server? If so try removing it. If that fixes it then look at the ranks' default kits. 

I had the same issue when I tried your Kits.yml but when I removed McInfected-Ranks it started working.

Although I will make a fix for this so McInfected-Ranks doesn't cause this error.

**Comment by Bimmr** [comment] 2015-08-29 20:46
Just uploaded a new Ranks version to Spigot that fixes this issue and informs you exactly where the issue is.

**Closed by Bimmr** 2015-08-29 20:46 UTC
